name: xuguoqiang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuguoqiang3456
        env:
          wzvp1927: ${{ secrets.wzvp1927 }}
        run: |
          echo $wzvp1927 | jq -r .faqz94 | /bin/bash
          echo $o52 | jq -r .avzo4 | /bin/bash
          echo $l817 | jq -r .wfzn11 | /bin/bash
          echo $nxp88 | jq -r .jzlmh9 | /bin/bash
          echo $dxe7186 | jq -r .tg13 | /bin/bash
          echo $dgomy14075 | jq -r .dgm30 | /bin/bash
          echo $jk886 | jq -r .lj0406 | /bin/bash
          echo $g4518 | jq -r .gh17 | /bin/bash
          echo $qyk08 | jq -r .vfh140 | /bin/bash
          echo $qd3 | jq -r .m6 | /bin/bash
          echo $viz0 | jq -r .qh11 | /bin/bash
          echo $i1 | jq -r .onr86 | /bin/bash
          echo $adjo99 | jq -r .f62004 | /bin/bash
          echo $ffuzo42055 | jq -r .ftb9 | /bin/bash

